### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by taylorr4**
@biggeeves, before we can approve this version, we just need to modify the title in the config with the new title name. If you approve this pull request, then create a new release (it doesn't have to be a new version, just a new github release), and send me the URL for the zip of the new release, then i'll approve this. Thanks!

### CODE REVIEW

**Comment by biggeeves** [comment]
Hi all,

 

The pull request was approved.

 

The new URL for the release is here:

 

https://github.com/biggeeves/Instance-Marker/archive/1.4.zip

 

This version is 1.4, what will the REDCap repo version be?  I’m trying to keep them in sync. 

 

- Greg

**Comment by taylorr4** [comment]
It could still be whatever version you want, even 1.0 or 1.3. The version is only controlled by whatever number you put into the repo submission survey. It doesn't even matter what you name the release or tag. What version number would you like it to be for this new release?

**Comment by biggeeves** [comment]
Got it.  How about 1.4; it would match the Github repo version.  

 

Greg=Simple.

**Comment by taylorr4** [comment]
1.4 has been approved and is now in the Repo. Thanks!

Rob Taylor
REDCap Development Team - Senior Developer (http://projectredcap.org<http://projectredcap.org/>)
Vanderbilt Institute for Clinical and Translational Research (VICTR)

**Pull request merged**
